name: Evaluate
version: ${project.version}
main: io.github.michailik.evaluate.Evaluate
authors: [ MichailiK ]
description: Allows evaluation of Nashorn code in Bukkit
website: https://github.com/MichailiK/Evaluate
default-permission: op
api-version: 1.13

commands:
  evaluate:
    description: Evaluates Nashorn code
    aliases: [ eval ]
    permission: evaluate.use
    usage: /evaluate <nashorn code>

  evaluateasynchronous:
    description: Evaluates Nashorn code outside the server thread.
    aliases: [ evaluateasync, evalasync, evala ]
    permission: evaluate.use
    usage: /evaluateasynchronous <nashorn code>

  evaluatereload:
    description: Reloads the Evaluate configuration file
    aliases: [ evalreload ]
    permission: evaluate.reload
    usage: /evalreload

permissions:
  evaluate.use:
    description: Allows evaluation of Nashorn code
    default: op

  evaluate.reload:
    description: Allows using the evaluatereload command
    default: op
